set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Darwin)
set(VCPKG_HIDDEN_SYMBOL_VISIBILITY)

set(CMAKE_C_COMPILER gcc-8)
set(CMAKE_ASM_COMPILER gcc-8)
set(CMAKE_CXX_COMPILER g++-8)