set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Darwin)
set(VCPKG_LINKER_FLAGS "-stdlib=libc++")
set(VCPKG_HIDDEN_SYMBOL_VISIBILITY)

set(VCPKG_C_COMPILER clang CACHE STRING "")
set(VCPKG_CXX_COMPILER clang++ CACHE STRING "")
