set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)

set(HOST x86_64-multilib-linux-musl)
set(CROSS ${HOST}-)

set(VCPKG_C_COMPILER ${CROSS}gcc)
set(VCPKG_ASM_COMPILER ${CROSS}gcc)
set(VCPKG_CXX_COMPILER ${CROSS}g++)
set(VCPKG_Fortran_COMPILER ${CROSS}gfortran)
set(VCPKG_STRIP ${CROSS}strip CACHE FILEPATH "")
set(VCPKG_AR ${CROSS}ar CACHE FILEPATH "")
set(VCPKG_RANLIB ${CROSS}gcc-ranlib CACHE FILEPATH "")
set(VCPKG_OBJDUMP ${CROSS}objdump CACHE FILEPATH "")

set(LINKER_EXECUTABLE ld.gold CACHE FILEPATH "")
set(VCPKG_LINKER_FLAGS "-static -fuse-ld=gold" CACHE STRING "")
set(VCPKG_HIDDEN_SYMBOL_VISIBILITY)
set(VCPKG_SYSROOT /tools/toolchains/x86_64-multilib-linux-musl/x86_64-multilib-linux-musl/sysroot)

#set(CMAKE_SKIP_RPATH ON)
#set(CMAKE_LINK_SEARCH_START_STATIC ON)
#set(CMAKE_LINK_SEARCH_END_STATIC ON)
